# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'user/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from user import user_pb2 as user_dot_user__pb2
from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user/service.proto\x12\x04user\x1a\x0fuser/user.proto\x1a\x13\x63ommon/common.proto\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"6\n\x15ValidateTokenResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"$\n\x13RefreshTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"%\n\x14RefreshTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t2\xda\x01\n\x0bUserService\x12\x39\n\x08Register\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x12\x30\n\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12+\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\n.user.User\x12\x31\n\nUpdateUser\x12\x17.user.UpdateUserRequest\x1a\n.user.User2\x9e\x01\n\x0b\x41uthService\x12H\n\rValidateToken\x12\x1a.user.ValidateTokenRequest\x1a\x1b.user.ValidateTokenResponse\x12\x45\n\x0cRefreshToken\x12\x19.user.RefreshTokenRequest\x1a\x1a.user.RefreshTokenResponseB#Z!github.com/ecoguard/protobuf/userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!github.com/ecoguard/protobuf/user'
  _globals['_VALIDATETOKENREQUEST']._serialized_start=66
  _globals['_VALIDATETOKENREQUEST']._serialized_end=103
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=105
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=159
  _globals['_REFRESHTOKENREQUEST']._serialized_start=161
  _globals['_REFRESHTOKENREQUEST']._serialized_end=197
  _globals['_REFRESHTOKENRESPONSE']._serialized_start=199
  _globals['_REFRESHTOKENRESPONSE']._serialized_end=236
  _globals['_USERSERVICE']._serialized_start=239
  _globals['_USERSERVICE']._serialized_end=457
  _globals['_AUTHSERVICE']._serialized_start=460
  _globals['_AUTHSERVICE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
