serve:
  port: 4000
  hostname: 0.0.0.0
  browser: false
  healthCheckEndpoint: /health
additionalTypeDefs: |
  type Subscription {
    issueCreated: IssueCreatedEvent
  }

  type IssueCreatedEvent {
    id: String
    tweet_id: String
    status: String
  }

additionalResolvers:
  - ./subscription.js

sources:
  - name: Classification
    handler:
      grpc:
        endpoint: classification-service:50053
        source:
          file: proto/classification/service.proto
          load:
            includeDirs:
              - proto

  - name: User
    handler:
      grpc:
        endpoint: user-auth-service:50051
        source:
          file: proto/user/service.proto
          load:
            includeDirs:
              - proto

  - name: Twitter
    handler:
      grpc:
        endpoint: twitter-service:50052
        source:
          file: proto/twitter/service.proto
          load:
            includeDirs:
              - proto

  - name: Notification
    handler:
      grpc:
        endpoint: notification-service:50054
        source:
          file: proto/notification/service.proto
          load:
            includeDirs:
              - proto

  - name: NLP
    handler:
      grpc:
        endpoint: nlp-service:50055
        source:
          file: proto/nlp/service.proto
          load:
            includeDirs:
              - proto

  - name: Blockchain
    handler:
      grpc:
        endpoint: blockchain-service:50056
        source:
          file: proto/blockchain/service.proto
          load:
            includeDirs:
              - proto

  - name: Issue
    handler:
      grpc:
        endpoint: issue-service:50057
        source:
          file: proto/issue/service.proto
          load:
            includeDirs:
              - proto

  - name: Asset
    handler:
      grpc:
        endpoint: asset-service:50058
        source:
          file: proto/asset/service.proto
          load:
            includeDirs:
              - proto
