apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  serviceName: vault-internal
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.19.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              cp /vault/config/vault.hcl /tmp/vault.hcl
              exec vault server -config=/tmp/vault.hcl
          ports:
            - containerPort: 8200
              name: api
            - containerPort: 8201
              name: cluster
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
            - name: VAULT_API_ADDR
              value: "http://$(POD_NAME).vault:8200"
            - name: VAULT_CLUSTER_ADDR
              value: "http://$(POD_NAME).vault-internal:8201"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: config
              mountPath: /vault/config
              readOnly: true
            - name: data
              mountPath: /vault/data
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
            initialDelaySeconds: 30
            periodSeconds: 10
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
      volumes:
        - name: config
          configMap:
            name: vault-config
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: vault
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
