# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common import common_pb2 as common_dot_common__pb2
from issue import service_pb2 as issue_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in issue/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IssueServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListIssues = channel.unary_unary(
                '/issue.IssueService/ListIssues',
                request_serializer=issue_dot_service__pb2.ListIssuesRequest.SerializeToString,
                response_deserializer=issue_dot_service__pb2.ListIssuesResponse.FromString,
                _registered_method=True)
        self.GetIssue = channel.unary_unary(
                '/issue.IssueService/GetIssue',
                request_serializer=issue_dot_service__pb2.GetIssueRequest.SerializeToString,
                response_deserializer=issue_dot_service__pb2.GetIssueResponse.FromString,
                _registered_method=True)
        self.ResolveIssue = channel.unary_unary(
                '/issue.IssueService/ResolveIssue',
                request_serializer=issue_dot_service__pb2.ResolveIssueRequest.SerializeToString,
                response_deserializer=issue_dot_service__pb2.ResolveIssueResponse.FromString,
                _registered_method=True)
        self.ListClusters = channel.unary_unary(
                '/issue.IssueService/ListClusters',
                request_serializer=common_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=issue_dot_service__pb2.ListClustersResponse.FromString,
                _registered_method=True)
        self.GetWordCloud = channel.unary_unary(
                '/issue.IssueService/GetWordCloud',
                request_serializer=common_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=issue_dot_service__pb2.GetWordCloudResponse.FromString,
                _registered_method=True)


class IssueServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListIssues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIssue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveIssue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClusters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWordCloud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IssueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListIssues': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIssues,
                    request_deserializer=issue_dot_service__pb2.ListIssuesRequest.FromString,
                    response_serializer=issue_dot_service__pb2.ListIssuesResponse.SerializeToString,
            ),
            'GetIssue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIssue,
                    request_deserializer=issue_dot_service__pb2.GetIssueRequest.FromString,
                    response_serializer=issue_dot_service__pb2.GetIssueResponse.SerializeToString,
            ),
            'ResolveIssue': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveIssue,
                    request_deserializer=issue_dot_service__pb2.ResolveIssueRequest.FromString,
                    response_serializer=issue_dot_service__pb2.ResolveIssueResponse.SerializeToString,
            ),
            'ListClusters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClusters,
                    request_deserializer=common_dot_common__pb2.Empty.FromString,
                    response_serializer=issue_dot_service__pb2.ListClustersResponse.SerializeToString,
            ),
            'GetWordCloud': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWordCloud,
                    request_deserializer=common_dot_common__pb2.Empty.FromString,
                    response_serializer=issue_dot_service__pb2.GetWordCloudResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'issue.IssueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('issue.IssueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IssueService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListIssues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issue.IssueService/ListIssues',
            issue_dot_service__pb2.ListIssuesRequest.SerializeToString,
            issue_dot_service__pb2.ListIssuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIssue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issue.IssueService/GetIssue',
            issue_dot_service__pb2.GetIssueRequest.SerializeToString,
            issue_dot_service__pb2.GetIssueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveIssue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issue.IssueService/ResolveIssue',
            issue_dot_service__pb2.ResolveIssueRequest.SerializeToString,
            issue_dot_service__pb2.ResolveIssueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issue.IssueService/ListClusters',
            common_dot_common__pb2.Empty.SerializeToString,
            issue_dot_service__pb2.ListClustersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWordCloud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issue.IssueService/GetWordCloud',
            common_dot_common__pb2.Empty.SerializeToString,
            issue_dot_service__pb2.GetWordCloudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
