# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asset/service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'asset/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61sset/service.proto\x12\x05\x61sset\"y\n\x05\x41sset\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x11\n\tmime_type\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\x03\x12\x10\n\x08metadata\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\x03\"Y\n\x12UploadAssetRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x11\n\tmime_type\x18\x03 \x01(\t\x12\x10\n\x08metadata\x18\x04 \x01(\t\"2\n\x13UploadAssetResponse\x12\x1b\n\x05\x61sset\x18\x01 \x01(\x0b\x32\x0c.asset.Asset\"\x1d\n\x0fGetAssetRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x10GetAssetResponse\x12\x1b\n\x05\x61sset\x18\x01 \x01(\x0b\x32\x0c.asset.Asset\"3\n\x11ListAssetsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08per_page\x18\x02 \x01(\x05\"A\n\x12ListAssetsResponse\x12\x1c\n\x06\x61ssets\x18\x01 \x03(\x0b\x32\x0c.asset.Asset\x12\r\n\x05total\x18\x02 \x01(\x05\x32\xd4\x01\n\x0c\x41ssetService\x12\x44\n\x0bUploadAsset\x12\x19.asset.UploadAssetRequest\x1a\x1a.asset.UploadAssetResponse\x12;\n\x08GetAsset\x12\x16.asset.GetAssetRequest\x1a\x17.asset.GetAssetResponse\x12\x41\n\nListAssets\x12\x18.asset.ListAssetsRequest\x1a\x19.asset.ListAssetsResponseB$Z\"github.com/ecoguard/protobuf/assetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asset.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"github.com/ecoguard/protobuf/asset'
  _globals['_ASSET']._serialized_start=30
  _globals['_ASSET']._serialized_end=151
  _globals['_UPLOADASSETREQUEST']._serialized_start=153
  _globals['_UPLOADASSETREQUEST']._serialized_end=242
  _globals['_UPLOADASSETRESPONSE']._serialized_start=244
  _globals['_UPLOADASSETRESPONSE']._serialized_end=294
  _globals['_GETASSETREQUEST']._serialized_start=296
  _globals['_GETASSETREQUEST']._serialized_end=325
  _globals['_GETASSETRESPONSE']._serialized_start=327
  _globals['_GETASSETRESPONSE']._serialized_end=374
  _globals['_LISTASSETSREQUEST']._serialized_start=376
  _globals['_LISTASSETSREQUEST']._serialized_end=427
  _globals['_LISTASSETSRESPONSE']._serialized_start=429
  _globals['_LISTASSETSRESPONSE']._serialized_end=494
  _globals['_ASSETSERVICE']._serialized_start=497
  _globals['_ASSETSERVICE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
