# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from asset import service_pb2 as asset_dot_service__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in asset/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AssetServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadAsset = channel.unary_unary(
                '/asset.AssetService/UploadAsset',
                request_serializer=asset_dot_service__pb2.UploadAssetRequest.SerializeToString,
                response_deserializer=asset_dot_service__pb2.UploadAssetResponse.FromString,
                _registered_method=True)
        self.GetAsset = channel.unary_unary(
                '/asset.AssetService/GetAsset',
                request_serializer=asset_dot_service__pb2.GetAssetRequest.SerializeToString,
                response_deserializer=asset_dot_service__pb2.GetAssetResponse.FromString,
                _registered_method=True)
        self.ListAssets = channel.unary_unary(
                '/asset.AssetService/ListAssets',
                request_serializer=asset_dot_service__pb2.ListAssetsRequest.SerializeToString,
                response_deserializer=asset_dot_service__pb2.ListAssetsResponse.FromString,
                _registered_method=True)


class AssetServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def UploadAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAssets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadAsset,
                    request_deserializer=asset_dot_service__pb2.UploadAssetRequest.FromString,
                    response_serializer=asset_dot_service__pb2.UploadAssetResponse.SerializeToString,
            ),
            'GetAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAsset,
                    request_deserializer=asset_dot_service__pb2.GetAssetRequest.FromString,
                    response_serializer=asset_dot_service__pb2.GetAssetResponse.SerializeToString,
            ),
            'ListAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAssets,
                    request_deserializer=asset_dot_service__pb2.ListAssetsRequest.FromString,
                    response_serializer=asset_dot_service__pb2.ListAssetsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asset.AssetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('asset.AssetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssetService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asset.AssetService/UploadAsset',
            asset_dot_service__pb2.UploadAssetRequest.SerializeToString,
            asset_dot_service__pb2.UploadAssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asset.AssetService/GetAsset',
            asset_dot_service__pb2.GetAssetRequest.SerializeToString,
            asset_dot_service__pb2.GetAssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asset.AssetService/ListAssets',
            asset_dot_service__pb2.ListAssetsRequest.SerializeToString,
            asset_dot_service__pb2.ListAssetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
