# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard/dashboard.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'dashboard/dashboard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x64\x61shboard/dashboard.proto\x12\tdashboard\"\x84\x01\n\x0bRecentTweet\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08tweet_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x17\n\x0f\x61uthor_username\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\x12\x1c\n\x14\x63lassification_label\x18\x06 \x01(\t\"\\\n\x0bRecentIssue\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\"\x98\x03\n\x0e\x44\x61shboardStats\x12\x14\n\x0ctotal_tweets\x18\x01 \x01(\x03\x12\x14\n\x0ctotal_issues\x18\x02 \x01(\x03\x12\x13\n\x0bopen_issues\x18\x03 \x01(\x03\x12\x17\n\x0fresolved_issues\x18\x04 \x01(\x03\x12\x1c\n\x14unread_notifications\x18\x05 \x01(\x03\x12\x19\n\x11\x62lockchain_blocks\x18\x06 \x01(\x03\x12\x1b\n\x13\x62lockchain_verified\x18\x07 \x01(\x08\x12\x43\n\x0eissues_by_type\x18\x08 \x03(\x0b\x32+.dashboard.DashboardStats.IssuesByTypeEntry\x12-\n\rrecent_tweets\x18\t \x03(\x0b\x32\x16.dashboard.RecentTweet\x12-\n\rrecent_issues\x18\n \x03(\x0b\x32\x16.dashboard.RecentIssue\x1a\x33\n\x11IssuesByTypeEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x42(Z&github.com/ecoguard/protobuf/dashboardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard.dashboard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/ecoguard/protobuf/dashboard'
  _globals['_DASHBOARDSTATS_ISSUESBYTYPEENTRY']._loaded_options = None
  _globals['_DASHBOARDSTATS_ISSUESBYTYPEENTRY']._serialized_options = b'8\001'
  _globals['_RECENTTWEET']._serialized_start=41
  _globals['_RECENTTWEET']._serialized_end=173
  _globals['_RECENTISSUE']._serialized_start=175
  _globals['_RECENTISSUE']._serialized_end=267
  _globals['_DASHBOARDSTATS']._serialized_start=270
  _globals['_DASHBOARDSTATS']._serialized_end=678
  _globals['_DASHBOARDSTATS_ISSUESBYTYPEENTRY']._serialized_start=627
  _globals['_DASHBOARDSTATS_ISSUESBYTYPEENTRY']._serialized_end=678
# @@protoc_insertion_point(module_scope)
