# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard/service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'dashboard/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dashboard import dashboard_pb2 as dashboard_dot_dashboard__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61shboard/service.proto\x12\tdashboard\x1a\x19\x64\x61shboard/dashboard.proto\"\x10\n\x0e\x44\x61shboardEmpty2T\n\x10\x44\x61shboardService\x12@\n\x08GetStats\x12\x19.dashboard.DashboardEmpty\x1a\x19.dashboard.DashboardStatsB(Z&github.com/ecoguard/protobuf/dashboardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/ecoguard/protobuf/dashboard'
  _globals['_DASHBOARDEMPTY']._serialized_start=65
  _globals['_DASHBOARDEMPTY']._serialized_end=81
  _globals['_DASHBOARDSERVICE']._serialized_start=83
  _globals['_DASHBOARDSERVICE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
