# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nlp/nlp.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'nlp/nlp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnlp/nlp.proto\x12\x03nlp\"\"\n\x12\x41nalyzeTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"m\n\x13\x41nalyzeTextResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x19\n\x11\x65xtracted_address\x18\x03 \x01(\t\x12\x18\n\x10paraphrased_text\x18\x04 \x01(\t\"!\n\x0eGeocodeRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"A\n\x0fGeocodeResponse\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\tB\"Z github.com/ecoguard/protobuf/nlpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlp.nlp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/ecoguard/protobuf/nlp'
  _globals['_ANALYZETEXTREQUEST']._serialized_start=22
  _globals['_ANALYZETEXTREQUEST']._serialized_end=56
  _globals['_ANALYZETEXTRESPONSE']._serialized_start=58
  _globals['_ANALYZETEXTRESPONSE']._serialized_end=167
  _globals['_GEOCODEREQUEST']._serialized_start=169
  _globals['_GEOCODEREQUEST']._serialized_end=202
  _globals['_GEOCODERESPONSE']._serialized_start=204
  _globals['_GEOCODERESPONSE']._serialized_end=269
# @@protoc_insertion_point(module_scope)
