# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nlp/service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'nlp/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nlp import nlp_pb2 as nlp_dot_nlp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11nlp/service.proto\x12\x03nlp\x1a\rnlp/nlp.proto2\xcc\x01\n\nNLPService\x12@\n\x0b\x41nalyzeText\x12\x17.nlp.AnalyzeTextRequest\x1a\x18.nlp.AnalyzeTextResponse\x12\x34\n\x07Geocode\x12\x13.nlp.GeocodeRequest\x1a\x14.nlp.GeocodeResponse\x12\x46\n\rGenerateReply\x12\x19.nlp.GenerateReplyRequest\x1a\x1a.nlp.GenerateReplyResponseB\"Z github.com/ecoguard/protobuf/nlpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlp.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/ecoguard/protobuf/nlp'
  _globals['_NLPSERVICE']._serialized_start=42
  _globals['_NLPSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
