# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nlp import nlp_pb2 as nlp_dot_nlp__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nlp/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NLPServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeText = channel.unary_unary(
                '/nlp.NLPService/AnalyzeText',
                request_serializer=nlp_dot_nlp__pb2.AnalyzeTextRequest.SerializeToString,
                response_deserializer=nlp_dot_nlp__pb2.AnalyzeTextResponse.FromString,
                _registered_method=True)
        self.Geocode = channel.unary_unary(
                '/nlp.NLPService/Geocode',
                request_serializer=nlp_dot_nlp__pb2.GeocodeRequest.SerializeToString,
                response_deserializer=nlp_dot_nlp__pb2.GeocodeResponse.FromString,
                _registered_method=True)
        self.GenerateReply = channel.unary_unary(
                '/nlp.NLPService/GenerateReply',
                request_serializer=nlp_dot_nlp__pb2.GenerateReplyRequest.SerializeToString,
                response_deserializer=nlp_dot_nlp__pb2.GenerateReplyResponse.FromString,
                _registered_method=True)


class NLPServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Geocode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NLPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeText': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeText,
                    request_deserializer=nlp_dot_nlp__pb2.AnalyzeTextRequest.FromString,
                    response_serializer=nlp_dot_nlp__pb2.AnalyzeTextResponse.SerializeToString,
            ),
            'Geocode': grpc.unary_unary_rpc_method_handler(
                    servicer.Geocode,
                    request_deserializer=nlp_dot_nlp__pb2.GeocodeRequest.FromString,
                    response_serializer=nlp_dot_nlp__pb2.GeocodeResponse.SerializeToString,
            ),
            'GenerateReply': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReply,
                    request_deserializer=nlp_dot_nlp__pb2.GenerateReplyRequest.FromString,
                    response_serializer=nlp_dot_nlp__pb2.GenerateReplyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nlp.NLPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nlp.NLPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NLPService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlp.NLPService/AnalyzeText',
            nlp_dot_nlp__pb2.AnalyzeTextRequest.SerializeToString,
            nlp_dot_nlp__pb2.AnalyzeTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Geocode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlp.NLPService/Geocode',
            nlp_dot_nlp__pb2.GeocodeRequest.SerializeToString,
            nlp_dot_nlp__pb2.GeocodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlp.NLPService/GenerateReply',
            nlp_dot_nlp__pb2.GenerateReplyRequest.SerializeToString,
            nlp_dot_nlp__pb2.GenerateReplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
