# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/notification.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'notification/notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fnotification/notification.proto\x12\x0cnotification\x1a\x13\x63ommon/common.proto\"\xc5\x01\n\x0cNotification\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\t\x12\r\n\x05title\x18\x05 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12%\n\ncreated_at\x18\x08 \x01(\x0b\x32\x11.common.Timestamp\x12\"\n\x07read_at\x18\t \x01(\x0b\x32\x11.common.Timestamp\"i\n\x17SendNotificationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\"&\n\x18SendNotificationResponse\x12\n\n\x02id\x18\x01 \x01(\t\"b\n\x17GetNotificationsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12&\n\npagination\x18\x03 \x01(\x0b\x32\x12.common.Pagination\"}\n\x18GetNotificationsResponse\x12\x31\n\rnotifications\x18\x01 \x03(\x0b\x32\x1a.notification.Notification\x12.\n\npagination\x18\x02 \x01(\x0b\x32\x1a.common.PaginationResponse\".\n\x0fMarkReadRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\tB+Z)github.com/ecoguard/protobuf/notificationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification.notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/ecoguard/protobuf/notification'
  _globals['_NOTIFICATION']._serialized_start=71
  _globals['_NOTIFICATION']._serialized_end=268
  _globals['_SENDNOTIFICATIONREQUEST']._serialized_start=270
  _globals['_SENDNOTIFICATIONREQUEST']._serialized_end=375
  _globals['_SENDNOTIFICATIONRESPONSE']._serialized_start=377
  _globals['_SENDNOTIFICATIONRESPONSE']._serialized_end=415
  _globals['_GETNOTIFICATIONSREQUEST']._serialized_start=417
  _globals['_GETNOTIFICATIONSREQUEST']._serialized_end=515
  _globals['_GETNOTIFICATIONSRESPONSE']._serialized_start=517
  _globals['_GETNOTIFICATIONSRESPONSE']._serialized_end=642
  _globals['_MARKREADREQUEST']._serialized_start=644
  _globals['_MARKREADREQUEST']._serialized_end=690
# @@protoc_insertion_point(module_scope)
