# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'notification/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from notification import notification_pb2 as notification_dot_notification__pb2
from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1anotification/service.proto\x12\x0cnotification\x1a\x1fnotification/notification.proto\x1a\x13\x63ommon/common.proto2\x95\x02\n\x13NotificationService\x12\x61\n\x10SendNotification\x12%.notification.SendNotificationRequest\x1a&.notification.SendNotificationResponse\x12\x61\n\x10GetNotifications\x12%.notification.GetNotificationsRequest\x1a&.notification.GetNotificationsResponse\x12\x38\n\x08MarkRead\x12\x1d.notification.MarkReadRequest\x1a\r.common.EmptyB+Z)github.com/ecoguard/protobuf/notificationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/ecoguard/protobuf/notification'
  _globals['_NOTIFICATIONSERVICE']._serialized_start=99
  _globals['_NOTIFICATIONSERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
