# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blockchain/service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'blockchain/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2
from blockchain import blockchain_pb2 as blockchain_dot_blockchain__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x62lockchain/service.proto\x12\nblockchain\x1a\x13\x63ommon/common.proto\x1a\x1b\x62lockchain/blockchain.proto2\xcc\x02\n\x11\x42lockchainService\x12[\n\x14RecordClassification\x12\'.blockchain.RecordClassificationRequest\x1a\x1a.blockchain.RecordResponse\x12S\n\x10RecordResolution\x12#.blockchain.RecordResolutionRequest\x1a\x1a.blockchain.RecordResponse\x12K\n\nGetHistory\x12\x1d.blockchain.GetHistoryRequest\x1a\x1e.blockchain.GetHistoryResponse\x12\x38\n\x0bVerifyChain\x12\r.common.Empty\x1a\x1a.blockchain.VerifyResponseB)Z\'github.com/ecoguard/protobuf/blockchainb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blockchain.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/ecoguard/protobuf/blockchain'
  _globals['_BLOCKCHAINSERVICE']._serialized_start=91
  _globals['_BLOCKCHAINSERVICE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
